name: STM32 Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # latest checkout

      - name: Install ARM GCC Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build project
        run: make

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: stm32-firmware
          path: |
            build/*.bin
            build/*.elf
